POST http://localhost:8080/signIn
Content-Type: application/json

{
  "email": "super.belovvadim@yandex.ru",
  "password": "password"
}

###

POST http://localhost:8080/signUp
Content-Type: application/json

{
  "id": "vadim_test",
  "email": "super.belovvadim@yandex.ru",
  "password": "password1234",
  "name": "Vadim",
  "surname": "Below",
  "phone": "79056456129"
}

###

GET http://localhost:8080/channels
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MzgsInN0ci1pZCI6InZhZGltX3Rlc3QiLCJyb2xlIjoiVVNFUiJ9.IeyUEj8vpJOjVJH_Cxs0mN6ha1a4TcLJ7Ft6Ju9yi4U

###

GET ws://localhost:8080/socket

###

POST http://localhost:8080/channels
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MzgsInN0ci1pZCI6InZhZGltX3Rlc3QiLCJyb2xlIjoiVVNFUiJ9.IeyUEj8vpJOjVJH_Cxs0mN6ha1a4TcLJ7Ft6Ju9yi4U

{
  "name": "channel1",
  "about": "just a test channel",
  "sourceType": 0,
  "type": 0
}

###

DELETE http://localhost:8080/channels/32

###

GET http://localhost:8080/channels/55/
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MzgsInN0ci1pZCI6InZhZGltX3Rlc3QiLCJyb2xlIjoiVVNFUiJ9.IeyUEj8vpJOjVJH_Cxs0mN6ha1a4TcLJ7Ft6Ju9yi4U

###

POST http://localhost:8080/channel/1/send
Content-Type: application/json

{
  "message": "test1"
}

###

PUT http://localhost:8080/channel/1/send
Content-Type: application/json

{
  "id": 1,
  "message": "test1_red"
}

###

DELETE http://localhost:8080/channel/1/send
Content-Type: application/json

{
  "id": 1
}
